import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'ar';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  isRTL: boolean;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  en: {
    // Navigation
    home: 'Home',
    about: 'About Us',
    products: 'Products',
    industrialProducts: 'Industrial Products',
    miningProducts: 'Mining Products',
    privatePort: 'Private Port',
    financial: 'Financial',
    tenders: 'ADS & Tender',
    news: 'News',
    contact: 'Contact Us',
    complaints: 'Complaints',
    
    // Hero Section
    heroSubtitle: 'Sinai Manganese Co. is the first and the largest producer of manganese ore in Egypt.',
    heroTitle: 'Sinai Manganese Co.',
    heroDescription:
      'Sinai Manganese Co. (SMC) was founded on May 18th 1957 to exploit the manganese deposits in the Sinai Peninsula. We operate the region’s only 36,000 MTPA electric furnace along with a 21 MW gas turbine power station.',
    heroPrimaryCta: 'Contact us',
    heroSecondaryCta: 'Discover our history',
    awardTitle: 'Awarded quality',
    awardDescription:
      'Our products are manufactured and rigorously tested to the highest international standards so you can rely on consistent ferroalloy performance.',
    
    // Stats
    statExperienceLabel: 'Years of experience',
    statExperienceDescription: 'We have more than 30 years of expertise producing Silicomanganese.',
    statWorkersLabel: 'Our workers',
    statWorkersDescription: 'Over 500 skilled employees power our furnaces, port, and logistics.',
    statProductionLabel: 'Annual production',
    statProductionDescription: 'We produce 36 thousand tons of Silicomanganese every year.',

    // Uses
    usesTitle: 'Uses of Silicomanganese',
    usesSubtitle: 'Versatile ferroalloys for critical industries',
    usesSteelTitle: 'Steel industry',
    usesSteelDescription: 'Silicomanganese is used as a deoxidizer and alloying agent.',
    usesChemicalTitle: 'Chemical industry',
    usesChemicalDescription: 'Influences the properties of the final chemical product.',
    usesWeldingTitle: 'Welding & separation',
    usesWeldingDescription: 'Powder applications in welding consumables and mineral separation.',

    // Energy & Lifestyle Solutions
    energyTitle: 'Energy solutions',
    energySubtitle: 'Expanding into integrated solar and green power systems.',
    energyChargeTitle: 'Charge electric vehicles',
    energyChargeDescription: 'Charge your e-car with clean energy from your own roof and save money.',
    energyHeatingTitle: 'Solar powered heating',
    energyHeatingDescription: 'Around 30% of home energy consumption goes to heating and hot water.',
    energyRoofTitle: 'Energy on the roof',
    energyRoofDescription: 'High-quality solar modules deliver dependable power for decades.',
    familyTitle: 'For you and your family',
    familyDescription:
      'Our robust glass-glass modules make solar sustainable in every way—reliably delivering high yields for many decades with a 30-year guarantee.',
    familyCta: 'View more',

    // About
    aboutTitle: 'About us',
    aboutExtendedTitle: 'A fully integrated industrial champion',
    aboutDescription:
      'SMC produces both high and low grades of manganese ore and operates an electrical furnace at Abu-Zinima, Sinai. We are the only Middle Eastern producer of Silicomanganese with our own 21 MW gas turbine power station.',
    aboutBullet1: 'Protection against mechanical stress',
    aboutBullet2: 'Protection against environmental influence',
    aboutBullet3: 'UV protection for lasting performance',
    aboutCta: 'About SMC',

    // Cases & References
    casesLabel: 'Latest cases',
    casesTitle: 'Our customers enjoy the sunny side of life – since 1993.',
    casesDescription: 'From high-yield rooftop systems to solar-powered heating, we tailor every installation.',
    case1Title: 'Energy on the roof',
    case1Description: 'High-quality solar modules form the powerful core of every system.',
    case2Title: 'Solar panels',
    case2Description: 'Discreet black modules deliver beautiful design with reliable output.',
    case3Title: 'Energy on the roof',
    case3Description: 'Robust construction ensures decades of dependable energy.',
    case4Title: 'Solar powered heating',
    case4Description: 'Smart thermal systems cover heating and warm-water demand efficiently.',

    // Product Overview
    productOverviewTitle: 'Product overview',
    productOverviewDescription: 'For great performance and beautiful design',
    productBullet1: 'High-quality design',
    productBullet2: 'Hard-wearing glass-glass composite',
    productBullet3: 'Reliable yields for decades',
    productCta: 'View more products',

    // Sustainability
    sustainabilityTitle: 'Thinking about tomorrow',
    sustainabilityDescription:
      'Many of our components are produced using 100% green energy, reducing emissions through shorter transportation routes.',
    sustainabilityBullet1: 'Careful use of natural resources',
    sustainabilityBullet2: 'Recyclable product design',
    sustainabilityBullet3: 'German-made components using renewable energy',

    // Modules CTA
    modulesTitle: 'Modules that ace every test',
    modulesDescription: 'Even the test of time—we engineer systems for multi-decade performance.',
    modulesCtaPrimary: 'Request quote now',
    modulesCtaSecondary: 'Get in touch',
    
    // Contact
    contactSectionTitle: 'Contact us',
    contactSectionSubtitle: 'Feel free to leave us a message and we will get back shortly.',
    contactHeadOfficeLabel: 'Head office',
    contactHeadOfficeValue: 'Abu Zenima – South Sinai, Egypt',
    contactCairoOfficeLabel: 'Cairo office',
    contactCairoOfficeValue: '1 Kasr El-Nile St., Cairo – Egypt',
    contactPhoneLabel: 'Phone numbers',
    contactPhoneValue: '25740005 / 25740217 / 257401096 / 25764458 / 2579429 / 00201282055059 / 00201099899572 / 00201099899389',
    contactEmailLabel: 'Email',
    contactEmailValue: 'info@smc-eg.com',
    contactFormFirstName: 'First name*',
    contactFormLastName: 'Last name*',
    contactFormEmail: 'Email address*',
    contactFormPhone: 'Phone number',
    contactFormMessage: 'Message',
    contactFormSubmit: 'Send Message',
    contactHeroBody: 'Share your industrial ambitions and our partnerships team will respond within one business day to plan a tailored working session.',
    contactHighlight1Title: '21 MW',
    contactHighlight1Subtitle: 'Private power station',
    contactHighlight2Title: '36K TON',
    contactHighlight2Subtitle: 'Silicomanganese output',
    contactHighlight3Title: '1957',
    contactHighlight3Subtitle: 'Founded in Egypt',
    contactFormSectionLabel: 'Engage',
    contactFormTitle: 'Send us a direct brief',
    contactFactoryLabel: 'Plant location',
    contactFactoryTitle: 'Abu Zenima Industrial Complex',
    contactFactoryDescription: 'Site visits, investor meetings, and training sessions can be scheduled through our strategic relations desk.',
    contactProcessTitle: 'What happens after you submit?',
    contactProcessStep1: 'We respond within a business day to confirm context.',
    contactProcessStep2: 'We arrange a discovery workshop with your team (onsite or remote).',
    contactProcessStep3: 'We craft an initial roadmap detailing timelines, squads, and governance.',

    // Legacy keys reused elsewhere
    contactUs: 'Contact Us',
    learnMore: 'Learn More',
    productsTitle: 'Uses of Silicomanganese',
    productsSubtitle: 'Industrial applications we support',
    awardsTitle: 'Awarded quality',
    awardsDescription:
      'Our products are manufactured and rigorously tested to the highest quality and manufacturing standards.',
    coreValuesLabel: 'Core values',
    coreValuesTitle: 'Our guiding principles',
    coreValuesSubtitle: 'Safety, reliability, and measurable value lead every project.',
    servicesLabel: 'Services',
    servicesTitle: 'Industrial capabilities',
    servicesSubtitle: 'From ore extraction to finished ferroalloys.',
    servicesCta: 'Explore service',
    projectsLabel: 'Projects',
    projectsTitle: 'Latest references',
    projectsSubtitle: 'Showcasing how we deliver sustainable energy and materials.',
    projectsCta: 'View all cases',
    projectsLearnMore: 'View case',
    ctaLabel: 'Get in touch',
    ctaTitle: 'Ready to partner with Sinai Manganese Co.?',
    ctaSubtitle: 'Share your requirements and we will tailor an industrial or energy solution.',
    ctaPrimary: 'Contact our team',
    ctaSecondary: 'Download company profile',
    footerDescription: 'Sinai Manganese Co. is the first and largest manganese ore producer in Egypt.',
    quickLinks: 'Useful links',
    followUs: 'Follow our social media',
    allRightsReserved: 'All Rights Reserved.',

    // Financial Page
    financialSubtitle: 'Maintaining strong financial performance through operational excellence and strategic growth',
    totalRevenue: 'Total Revenue',
    netProfit: 'Net Profit',
    exportVolume: 'Export Volume',
    productionEfficiency: 'Production Efficiency',
    marketShare: 'Market Share',
    growthRate: 'Growth Rate',
    revenue: 'Revenue',
    profit: 'Profit',
    production: 'Production',
    target: 'Target',
    expenses: 'Expenses',
    revenueDescription: 'Total annual revenue from all operations',
    profitDescription: 'Net profit after all expenses',
    exportDescription: 'Percentage of production exported globally',
    efficiencyDescription: 'Overall operational efficiency rating',
    marketShareDescription: 'Leading position in Egyptian manganese market',
    growthDescription: 'Year-over-year growth rate',
    revenueGrowth: 'Revenue Growth (5 Years)',
    revenueGrowthDescription: 'Steady growth in revenue and profitability over the past five years',
    productionPerformance: 'Monthly Production vs Target',
    productionPerformanceDescription: 'Production performance compared to monthly targets',
    exportDistribution: 'Export Distribution',
    exportDistributionDescription: 'Geographic distribution of exports by region',
    exportEurope: 'Europe',
    exportAsia: 'Asia',
    exportMiddleEast: 'Middle East',
    exportAfrica: 'Africa',
    quarterlyPerformance: 'Quarterly Performance',
    quarterlyPerformanceDescription: 'Revenue, expenses, and profit breakdown by quarter',
    investmentBreakdown: 'Investment Breakdown',
    investmentBreakdownDescription: 'Distribution of investments across different categories',
    investmentInfrastructure: 'Infrastructure',
    investmentTechnology: 'Technology',
    investmentSustainability: 'Sustainability',
    investmentResearch: 'Research & Development',
    efficiencyMetrics: 'Operational Efficiency Metrics',
    efficiencyMetricsDescription: 'Key performance indicators across different operational areas',
    efficiencyProduction: 'Production Efficiency',
    efficiencyQuality: 'Quality Control',
    efficiencyEnergy: 'Energy Efficiency',
    efficiencyLogistics: 'Logistics & Supply Chain',
    jan: 'Jan',
    feb: 'Feb',
    mar: 'Mar',
    apr: 'Apr',
    may: 'May',
    jun: 'Jun',

    // Products Section
    productsSectionLabel: 'Our Products',
    productsSectionTitle: 'High-Quality Industrial & Mining Products',
    productsSectionSubtitle: 'Comprehensive range of premium products manufactured to international standards',
    industrialProductsDescription: 'Advanced industrial products for various manufacturing applications',
    miningProductsDescription: 'Premium raw materials extracted and processed from our mining operations',
    productSilicomanganese: 'Silicomanganese',
    productSilicomanganeseDesc: 'High-quality ferroalloy used in steel production as a deoxidizer and alloying agent. Produced in our 36,000 MTPA electric furnace.',
    productCalcinedGypsum: 'Calcined Gypsum',
    productCalcinedGypsumDesc: 'Processed gypsum from our Ras Malaab facility, ideal for construction, cement, and industrial applications.',
    productKaolin: 'Kaolin',
    productKaolinDesc: 'Premium quality kaolin from Sinai deposits, one of the best in the Middle East. Used in refractory, cement, ceramic, and paper industries.',
    productSilicaSand: 'Silica Sand',
    productSilicaSandDesc: 'High-purity silica sand from South Sinai and Zaafarana. Available in multiple grades for glass manufacturing, crystal, and various industrial uses.',
    productRawGypsum: 'Raw Gypsum',
    productRawGypsumDesc: 'Natural gypsum ore from Ras Malaab, South Sinai. Exported to Japan and African countries for various industrial applications.',
    productIronOxide: 'Iron Oxide',
    productIronOxideDesc: 'High-grade iron oxide for industrial and chemical applications, meeting international quality standards.',
    productFineManganese: 'Fine Manganese',
    productFineManganeseDesc: 'Premium fine manganese powder for specialized industrial applications and alloy production.',
    viewAllProducts: 'View All Products',
    backToProducts: 'Back to Products',
    backToNews: 'Back to News',
    specifications: 'Specifications',
    applications: 'Applications',
    keyFeatures: 'Key Features',
    viewAllNews: 'View All News',

    // Dashboard
    dashboard: 'Dashboard',
    dashboardSubtitle: 'Manage your website content and data',
    settings: 'Settings',
    totalProducts: 'Total Products',
    totalNews: 'Total News',
    totalContacts: 'Total Contacts',
    totalComplaints: 'Total Complaints',
    overview: 'Overview',
    contacts: 'Contacts',
    recentActivity: 'Recent Activity',
    quickStats: 'Quick Stats',
    search: 'Search',
    addProduct: 'Add Product',
    addNews: 'Add News',
    name: 'Name',
    category: 'Category',
    views: 'Views',
    status: 'Status',
    actions: 'Actions',
    title: 'Title',
    date: 'Date',
    login: 'Login',
    logout: 'Logout',
    adminLogin: 'Admin Login',
    loginDescription: 'Sign in to access the dashboard',
    emailPlaceholder: 'admin@smc-eg.com',
    passwordPlaceholder: 'Enter your password',
    loggingIn: 'Logging in...',
    loginSuccess: 'Login successful!',
    loginError: 'Invalid email or password',
    demoCredentials: 'Demo Credentials:',
    statistics: 'Statistics',
    pageContent: 'Page Content',
    heroBanners: 'Hero Banners',
    mediaLibrary: 'Media Library',
    manageProducts: 'Manage all products',
    manageNews: 'Manage all news articles',
    manageUsers: 'Manage users and permissions',
    manageMedia: 'Manage all media files',
    manageHeroBanners: 'Manage hero section banners',
    editPageContent: 'Edit content for all pages',
    manageSiteSettings: 'Manage website settings',
    viewAnalytics: 'View website analytics and statistics',
    manageContacts: 'Manage contact messages',
    manageComplaints: 'Manage customer complaints',
    editProduct: 'Edit Product',
    editNews: 'Edit News',
    addUser: 'Add User',
    editUser: 'Edit User',
    addBanner: 'Add Banner',
    editBanner: 'Edit Banner',
    uploadMedia: 'Upload Media',
    uploadImage: 'Upload Image',
    productsList: 'Products List',
    newsList: 'News List',
    usersList: 'Users List',
    contactsList: 'Contacts List',
    complaintsList: 'Complaints List',
    description: 'Description',
    subtitle: 'Subtitle',
    order: 'Order',
    active: 'Active',
    image: 'Image',
    content: 'Content',
    saveAll: 'Save All',
    selectPage: 'Select Page',
    general: 'General',
    generalSettings: 'General Settings',
    contactInformation: 'Contact Information',
    siteName: 'Site Name',
    headOffice: 'Head Office',
    cairoOffice: 'Cairo Office',
    permissions: 'Permissions',
    role: 'Role',
    cancel: 'Cancel',
    save: 'Save',
  },
  ar: {
    home: 'الرئيسية',
    about: 'من نحن',
    products: 'المنتجات',
    industrialProducts: 'المنتجات الصناعية',
    miningProducts: 'منتجات التعدين',
    privatePort: 'الميناء الخاص',
    financial: 'المالية',
    tenders: 'الإعلانات والمناقصات',
    news: 'الأخبار',
    contact: 'اتصل بنا',
    complaints: 'شكاوى العملاء',

    heroSubtitle: 'شركة سيناء للمنجنيز هي الأولى والأكبر في إنتاج خام المنجنيز في مصر.',
    heroTitle: 'شركة سيناء للمنجنيز',
    heroDescription:
      'تأسست شركة سيناء للمنجنيز في 18 مايو 1957 لاستغلال رواسب المنجنيز في شبه جزيرة سيناء. ندير الفرن الكهربائي الوحيد في المنطقة بطاقة 36 ألف طن سنويًا إلى جانب محطة غازية بقدرة 21 ميجاوات.',
    heroPrimaryCta: 'تواصل معنا',
    heroSecondaryCta: 'اكتشف تاريخنا',
    awardTitle: 'جودة معتمدة',
    awardDescription: 'نصنع منتجاتنا ونختبرها وفقًا لأعلى المعايير الدولية لتضمن أداءً متسقًا للسبائك الحديدية.',

    statExperienceLabel: 'سنوات الخبرة',
    statExperienceDescription: 'لدينا أكثر من 30 عامًا من الخبرة في إنتاج السيليكومنجنيز.',
    statWorkersLabel: 'فريق العمل',
    statWorkersDescription: 'أكثر من 500 موظف يديرون أفراننا وميناءنا ولوجستياتنا.',
    statProductionLabel: 'الإنتاج السنوي',
    statProductionDescription: 'ننتج 36 ألف طن من السيليكومنجنيز كل عام.',

    usesTitle: 'استخدامات السيليكومنجنيز',
    usesSubtitle: 'حلول متعددة للقطاعات الحيوية',
    usesSteelTitle: 'صناعة الصلب',
    usesSteelDescription: 'يستخدم كعامل إزالة الأكسدة وعامل صناعة السبائك.',
    usesChemicalTitle: 'الصناعة الكيميائية',
    usesChemicalDescription: 'التأثير على خصائص المنتج الكيميائي النهائي.',
    usesWeldingTitle: 'اللحام والفصل',
    usesWeldingDescription: 'يُستخدم في مواد اللحام وعملية الفصل المعدني.',

    energyTitle: 'حلول الطاقة',
    energySubtitle: 'نوسع نشاطنا إلى أنظمة الطاقة الشمسية والطاقة الخضراء المتكاملة.',
    energyChargeTitle: 'شحن المركبات الكهربائية',
    energyChargeDescription: 'اشحن سيارتك بالطاقة النظيفة من سطح منزلك ووفّر التكاليف.',
    energyHeatingTitle: 'تدفئة بالطاقة الشمسية',
    energyHeatingDescription: 'حوالي 30٪ من استهلاك الطاقة المنزلي يذهب للتدفئة والمياه.',
    energyRoofTitle: 'طاقة على السطح',
    energyRoofDescription: 'وحدات شمسية عالية الجودة تضمن طاقة موثوقة لعقود.',
    familyTitle: 'من أجلك ولعائلتك',
    familyDescription:
      'البناء الزجاجي المزدوج يجعل وحداتنا الشمسية مستدامة بكل المقاييس مع ضمان لمدة 30 عامًا وعوائد مرتفعة.',
    familyCta: 'عرض المزيد',

    aboutTitle: 'من نحن',
    aboutExtendedTitle: 'شركة صناعية متكاملة',
    aboutDescription:
      'تنتج شركة سيناء للمنجنيز الدرجات العالية والمنخفضة من خام المنجنيز وتدير فرنًا كهربائيًا في أبو زنيمة، وهي المنتج الوحيد للسيليكومنجنيز في الشرق الأوسط مع محطة كهرباء خاصة بقدرة 21 ميجاوات.',
    aboutBullet1: 'حماية ضد الإجهادات الميكانيكية',
    aboutBullet2: 'حماية من العوامل البيئية',
    aboutBullet3: 'حماية من الأشعة فوق البنفسجية',
    aboutCta: 'تعرف علينا',

    casesLabel: 'أحدث المشاريع',
    casesTitle: 'عملاؤنا يستمتعون بجانب الحياة المشمس منذ 1993.',
    casesDescription: 'من الأنظمة على الأسطح إلى التدفئة بالطاقة الشمسية، نصمم كل نظام بعناية.',
    case1Title: 'طاقة على السطح',
    case1Description: 'تشكل وحداتنا عالية الجودة القلب النابض لنظامك.',
    case2Title: 'ألواح شمسية',
    case2Description: 'تصميم أسود أنيق مع أداء موثوق.',
    case3Title: 'طاقة على السطح',
    case3Description: 'هيكل متين يضمن طاقة لعقود طويلة.',
    case4Title: 'تدفئة بالطاقة الشمسية',
    case4Description: 'حلول ذكية تغطي احتياجات التدفئة والمياه الساخنة بكفاءة.',

    productOverviewTitle: 'نظرة على المنتجات',
    productOverviewDescription: 'أداء عالٍ وتصميم أنيق',
    productBullet1: 'تصميم عالي الجودة',
    productBullet2: 'تركيب زجاجي متين',
    productBullet3: 'عوائد موثوقة لعقود',
    productCta: 'استعرض المنتجات',

    sustainabilityTitle: 'نفكر في الغد',
    sustainabilityDescription:
      'يتم تصنيع العديد من مكوناتنا في ألمانيا باستخدام طاقة خضراء بنسبة 100٪ مما يقلل الانبعاثات والمسافات.',
    sustainabilityBullet1: 'استخدام مدروس للموارد الطبيعية',
    sustainabilityBullet2: 'تصميم قابل لإعادة التدوير',
    sustainabilityBullet3: 'مكونات ألمانية الصنع بطاقة متجددة',

    modulesTitle: 'وحدات تجتاز كل الاختبارات',
    modulesDescription: 'حتى اختبار الزمن – نصمم الأنظمة لأداء يمتد لعقود.',
    modulesCtaPrimary: 'اطلب عرض سعر',
    modulesCtaSecondary: 'تواصل معنا',

    contactSectionTitle: 'اتصل بنا',
    contactSectionSubtitle: 'لا تتردد في ترك رسالة وسنعاود الاتصال بك قريباً.',
    contactHeadOfficeLabel: 'المقر الرئيسي',
    contactHeadOfficeValue: 'أبو زنيمة – جنوب سيناء، مصر',
    contactCairoOfficeLabel: 'مكتب القاهرة',
    contactCairoOfficeValue: '1 شارع قصر النيل، القاهرة – مصر',
    contactPhoneLabel: 'أرقام الهاتف',
    contactPhoneValue: '25740005 / 25740217 / 257401096 / 25764458 / 2579429 / 00201282055059 / 00201099899572 / 00201099899389',
    contactEmailLabel: 'البريد الإلكتروني',
    contactEmailValue: 'info@smc-eg.com',
    contactFormFirstName: 'الاسم الأول*',
    contactFormLastName: 'الاسم الأخير*',
    contactFormEmail: 'البريد الإلكتروني*',
    contactFormPhone: 'رقم الهاتف',
    contactFormMessage: 'الرسالة',
    contactFormSubmit: 'أرسل الرسالة',
    contactHeroBody: 'شاركنا أهدافك الصناعية وسيتواصل معك فريق الشراكات خلال يوم عمل واحد لترتيب جلسة عمل مخصصة.',
    contactHighlight1Title: '21 ميجاوات',
    contactHighlight1Subtitle: 'محطة طاقة خاصة',
    contactHighlight2Title: '36 ألف طن',
    contactHighlight2Subtitle: 'طاقة إنتاج السيليكومنجنيز',
    contactHighlight3Title: '1957',
    contactHighlight3Subtitle: 'عام التأسيس في مصر',
    contactFormSectionLabel: 'التواصل',
    contactFormTitle: 'أرسل موجزاً مباشراً',
    contactFactoryLabel: 'موقع المصنع',
    contactFactoryTitle: 'مجمع أبو زنيمة الصناعي',
    contactFactoryDescription: 'يمكن ترتيب جولات ميدانية واجتماعات المستثمرين وبرامج التدريب عبر فريق العلاقات الاستراتيجية لدينا.',
    contactProcessTitle: 'ماذا يحدث بعد الإرسال؟',
    contactProcessStep1: 'نتواصل خلال يوم عمل لتأكيد التفاصيل.',
    contactProcessStep2: 'نحدد جلسة استكشافية مع فريقك (حضوريًا أو عن بُعد).',
    contactProcessStep3: 'نصيغ خارطة طريق مبدئية تشمل الجدول الزمني والكوادر والحكومة.',

    contactUs: 'اتصل بنا',
    learnMore: 'اعرف المزيد',
    productsTitle: 'استخدامات السيليكومنجنيز',
    productsSubtitle: 'حلول صناعية ندعمها',
    awardsTitle: 'جودة معتمدة',
    awardsDescription: 'يتم تصنيع منتجاتنا واختبارها وفقًا لأعلى معايير الجودة.',
    coreValuesLabel: 'قيمنا',
    coreValuesTitle: 'مبادئنا',
    coreValuesSubtitle: 'السلامة والموثوقية والقيمة الملموسة.',
    servicesLabel: 'الخدمات',
    servicesTitle: 'قدراتنا الصناعية',
    servicesSubtitle: 'من استخراج الخام إلى السبائك النهائية.',
    servicesCta: 'اكتشف الخدمة',
    projectsLabel: 'المشاريع',
    projectsTitle: 'أحدث المراجع',
    projectsSubtitle: 'نستعرض كيف نقدم الطاقة والمواد المستدامة.',
    projectsCta: 'عرض كل الحالات',
    projectsLearnMore: 'عرض الحالة',
    ctaLabel: 'للتواصل',
    ctaTitle: 'جاهزون للشراكة مع شركة سيناء للمنجنيز؟',
    ctaSubtitle: 'شاركنا متطلباتك لنصمم حلاً صناعياً أو طاقوياً مناسباً.',
    ctaPrimary: 'تواصل مع فريقنا',
    ctaSecondary: 'حمّل ملف الشركة',
    footerDescription: 'شركة سيناء للمنجنيز هي أول وأكبر منتج لخام المنجنيز في مصر.',
    quickLinks: 'روابط مفيدة',
    followUs: 'تابعنا على وسائل التواصل',
    allRightsReserved: 'جميع الحقوق محفوظة.',

    // Financial Page
    financialSubtitle: 'الحفاظ على أداء مالي قوي من خلال التميز التشغيلي والنمو الاستراتيجي',
    totalRevenue: 'إجمالي الإيرادات',
    netProfit: 'صافي الربح',
    exportVolume: 'حجم التصدير',
    productionEfficiency: 'كفاءة الإنتاج',
    marketShare: 'الحصة السوقية',
    growthRate: 'معدل النمو',
    revenue: 'الإيرادات',
    profit: 'الربح',
    production: 'الإنتاج',
    target: 'الهدف',
    expenses: 'المصروفات',
    revenueDescription: 'إجمالي الإيرادات السنوية من جميع العمليات',
    profitDescription: 'صافي الربح بعد جميع المصروفات',
    exportDescription: 'نسبة الإنتاج المصدر عالمياً',
    efficiencyDescription: 'تصنيف الكفاءة التشغيلية الإجمالية',
    marketShareDescription: 'المركز الرائد في سوق المنجنيز المصري',
    growthDescription: 'معدل النمو على أساس سنوي',
    revenueGrowth: 'نمو الإيرادات (5 سنوات)',
    revenueGrowthDescription: 'نمو مستمر في الإيرادات والربحية على مدى السنوات الخمس الماضية',
    productionPerformance: 'الإنتاج الشهري مقابل الهدف',
    productionPerformanceDescription: 'أداء الإنتاج مقارنة بالأهداف الشهرية',
    exportDistribution: 'توزيع الصادرات',
    exportDistributionDescription: 'التوزيع الجغرافي للصادرات حسب المنطقة',
    exportEurope: 'أوروبا',
    exportAsia: 'آسيا',
    exportMiddleEast: 'الشرق الأوسط',
    exportAfrica: 'أفريقيا',
    quarterlyPerformance: 'الأداء الربعي',
    quarterlyPerformanceDescription: 'تفصيل الإيرادات والمصروفات والربح حسب الربع',
    investmentBreakdown: 'تفصيل الاستثمارات',
    investmentBreakdownDescription: 'توزيع الاستثمارات عبر فئات مختلفة',
    investmentInfrastructure: 'البنية التحتية',
    investmentTechnology: 'التكنولوجيا',
    investmentSustainability: 'الاستدامة',
    investmentResearch: 'البحث والتطوير',
    efficiencyMetrics: 'مؤشرات الكفاءة التشغيلية',
    efficiencyMetricsDescription: 'مؤشرات الأداء الرئيسية عبر مجالات تشغيلية مختلفة',
    efficiencyProduction: 'كفاءة الإنتاج',
    efficiencyQuality: 'مراقبة الجودة',
    efficiencyEnergy: 'كفاءة الطاقة',
    efficiencyLogistics: 'اللوجستيات وسلسلة التوريد',
    jan: 'يناير',
    feb: 'فبراير',
    mar: 'مارس',
    apr: 'أبريل',
    may: 'مايو',
    jun: 'يونيو',

    // Products Section
    productsSectionLabel: 'منتجاتنا',
    productsSectionTitle: 'منتجات صناعية وتعدينية عالية الجودة',
    productsSectionSubtitle: 'مجموعة شاملة من المنتجات المميزة المصنعة وفقاً للمعايير الدولية',
    industrialProductsDescription: 'منتجات صناعية متقدمة لتطبيقات التصنيع المختلفة',
    miningProductsDescription: 'مواد خام مميزة مستخرجة ومعالجة من عمليات التعدين لدينا',
    productSilicomanganese: 'سيليكون منجنيز',
    productSilicomanganeseDesc: 'سبيكة حديدية عالية الجودة تستخدم في إنتاج الصلب كعامل إزالة الأكسدة وعامل صناعة السبائك. يتم إنتاجها في فرننا الكهربائي بطاقة 36,000 طن سنوياً.',
    productCalcinedGypsum: 'جبس مكلسن',
    productCalcinedGypsumDesc: 'جبس معالج من منشأة رأس ملعب لدينا، مثالي للبناء والأسمنت والتطبيقات الصناعية.',
    productKaolin: 'كاولين',
    productKaolinDesc: 'كاولين عالي الجودة من رواسب سيناء، أحد الأفضل في الشرق الأوسط. يستخدم في صناعات الحراريات والأسمنت والسيراميك والورق.',
    productSilicaSand: 'رمال سيلكا',
    productSilicaSandDesc: 'رمال سيلكا عالية النقاء من جنوب سيناء والزعفرانة. متوفرة بدرجات متعددة لتصنيع الزجاج والكريستال واستخدامات صناعية متنوعة.',
    productRawGypsum: 'جبس خام',
    productRawGypsumDesc: 'خام الجبس الطبيعي من رأس ملعب، جنوب سيناء. يتم تصديره إلى اليابان والدول الأفريقية لتطبيقات صناعية متنوعة.',
    productIronOxide: 'أكسيد الحديد',
    productIronOxideDesc: 'أكسيد حديد عالي الجودة للتطبيقات الصناعية والكيميائية، يلبي المعايير الدولية للجودة.',
    productFineManganese: 'منجنيز ناعم',
    productFineManganeseDesc: 'مسحوق منجنيز ناعم مميز للتطبيقات الصناعية المتخصصة وإنتاج السبائك.',
    viewAllProducts: 'عرض جميع المنتجات',
    backToProducts: 'العودة للمنتجات',
    backToNews: 'العودة للأخبار',
    specifications: 'المواصفات',
    applications: 'التطبيقات',
    keyFeatures: 'المميزات الرئيسية',
    viewAllNews: 'عرض جميع الأخبار',

    // Dashboard
    dashboard: 'لوحة التحكم',
    dashboardSubtitle: 'إدارة محتوى الموقع والبيانات',
    settings: 'الإعدادات',
    totalProducts: 'إجمالي المنتجات',
    totalNews: 'إجمالي الأخبار',
    totalContacts: 'إجمالي الاتصالات',
    totalComplaints: 'إجمالي الشكاوى',
    overview: 'نظرة عامة',
    contacts: 'الاتصالات',
    recentActivity: 'النشاط الأخير',
    quickStats: 'إحصائيات سريعة',
    search: 'بحث',
    addProduct: 'إضافة منتج',
    addNews: 'إضافة خبر',
    name: 'الاسم',
    category: 'الفئة',
    views: 'المشاهدات',
    status: 'الحالة',
    actions: 'الإجراءات',
    title: 'العنوان',
    date: 'التاريخ',
    login: 'تسجيل الدخول',
    logout: 'تسجيل الخروج',
    adminLogin: 'تسجيل دخول الأدمن',
    loginDescription: 'سجل الدخول للوصول إلى لوحة التحكم',
    emailPlaceholder: 'admin@smc-eg.com',
    passwordPlaceholder: 'أدخل كلمة المرور',
    loggingIn: 'جاري تسجيل الدخول...',
    loginSuccess: 'تم تسجيل الدخول بنجاح!',
    loginError: 'البريد الإلكتروني أو كلمة المرور غير صحيحة',
    demoCredentials: 'بيانات الدخول التجريبية:',
    statistics: 'الإحصائيات',
    pageContent: 'محتوى الصفحات',
    heroBanners: 'بنرات الهيرو',
    mediaLibrary: 'مكتبة الوسائط',
    manageProducts: 'إدارة جميع المنتجات',
    manageNews: 'إدارة جميع المقالات',
    manageUsers: 'إدارة المستخدمين والصلاحيات',
    manageMedia: 'إدارة جميع ملفات الوسائط',
    manageHeroBanners: 'إدارة بنرات قسم الهيرو',
    editPageContent: 'تعديل محتوى جميع الصفحات',
    manageSiteSettings: 'إدارة إعدادات الموقع',
    viewAnalytics: 'عرض إحصائيات وتحليلات الموقع',
    manageContacts: 'إدارة رسائل الاتصال',
    manageComplaints: 'إدارة شكاوى العملاء',
    editProduct: 'تعديل منتج',
    editNews: 'تعديل خبر',
    addUser: 'إضافة مستخدم',
    editUser: 'تعديل مستخدم',
    addBanner: 'إضافة بانر',
    editBanner: 'تعديل بانر',
    uploadMedia: 'رفع وسائط',
    uploadImage: 'رفع صورة',
    productsList: 'قائمة المنتجات',
    newsList: 'قائمة الأخبار',
    usersList: 'قائمة المستخدمين',
    contactsList: 'قائمة الاتصالات',
    complaintsList: 'قائمة الشكاوى',
    description: 'الوصف',
    subtitle: 'العنوان الفرعي',
    order: 'الترتيب',
    active: 'نشط',
    image: 'صورة',
    content: 'المحتوى',
    saveAll: 'حفظ الكل',
    selectPage: 'اختر الصفحة',
    general: 'عام',
    generalSettings: 'الإعدادات العامة',
    contactInformation: 'معلومات الاتصال',
    siteName: 'اسم الموقع',
    headOffice: 'المكتب الرئيسي',
    cairoOffice: 'مكتب القاهرة',
    permissions: 'الصلاحيات',
    role: 'الدور',
    cancel: 'إلغاء',
    save: 'حفظ',
  },
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  useEffect(() => {
    // Update document direction based on language
    if (typeof document !== 'undefined') {
      document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
      document.documentElement.lang = language;
    }
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations.en] || key;
  };

  const isRTL = language === 'ar';

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isRTL }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
